
export const PLACEHOLDER_IMG = "https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&q=80&w=800";

export const TRANSLATIONS = {
    en: {
        dashboard: "Dashboard",
        wishlist: "Wishlist / Saved",
        analytics: "Analytics",
        legal: "Legal Assistant",
        logout: "Logout",
        search_placeholder: "Search sermons, news...",
        trending_title: "Trending Gospel Videos",
        news_title: "Latest Christian News",
        admin_panel: "Admin Panel",
        legal_intro: "I am your AI Legal Assistant for minority rights in India.\n\nYou can ask me questions like:\n- What are my rights as a Christian institution?\n- How do I register a minority school?\n- What is Article 30?",
        verified_ai_response: "Verified AI Response",
        read_aloud: "READ ALOUD",
        news_btn: "News",
        videos_btn: "Videos",
        min_read: "min read",
        recently: "Recently",
        legal_disclaimer: "AI can make mistakes. Please consult with a qualified legal professional for official advice.",
        search_news_placeholder: "Search news articles...",
        search_videos_placeholder: "Search videos...",
        found_results: "Results for",
        no_news: "No news found",
        no_videos: "No videos found",
        no_results: "No results found matching your query.",
        loading: "Loading content...",
        search: "Search",
        clear: "Clear",
        read_more: "Read More",
        watch_now: "Watch Now",
        saved: "Saved",
        save: "Save",
        Sports: "Sports",
        Technology: "Technology",
        Science: "Science",
        Business: "Business",
        Entertainment: "Entertainment",
        Politics: "Politics",
        Christianity: "Christianity"
    },
    hi: {
        dashboard: "डैशबोर्ड",
        wishlist: "सहेजे गए",
        analytics: "विश्लेषण",
        legal: "कानूनी सहायक",
        logout: "लॉग आउट",
        search_placeholder: "उपदेश, समाचार खोजें...",
        trending_title: "ट्रेंडिंग सुसमाचार वीडियो",
        news_title: "नवीनतम ईसाई समाचार",
        admin_panel: "एडमिन पैनल",
        legal_intro: "<p>मैं भारत में अल्पसंख्यक अधिकारों के लिए आपका <b>AI कानूनी सहायक</b> हूं।</p><p>आप मुझसे प्रश्न पूछ सकते हैं जैसे:</p><ul><li>ईसाई संस्थान के रूप में मेरे अधिकार क्या हैं?</li><li>अल्पसंख्यक स्कूल कैसे पंजीकृत करें?</li><li>अनुच्छेद 30 क्या है?</li></ul>",
        verified_ai_response: "सत्यापित AI प्रतिक्रिया",
        read_aloud: "जोर से पढ़ें",
        news_btn: "समाचार",
        videos_btn: "वीडियो",
        min_read: "मिनट पढ़ें",
        recently: "हाल ही में",
        legal_disclaimer: "AI गलतियाँ कर सकता है। आधिकारिक सलाह के लिए कृपया किसी योग्य कानूनी पेशेवर से परामर्श लें।",
        search_news_placeholder: "समाचार लेख खोजें...",
        search_videos_placeholder: "वीडियो खोजें...",
        found_results: "परिणाम मिले",
        no_news: "कोई समाचार नहीं मिला",
        no_videos: "कोई वीडियो नहीं मिला",
        no_results: "आपकी खोज से मेल खाते कोई परिणाम नहीं मिले",
        loading: "लोड हो रहा है...",
        search: "खोजें",
        clear: "साफ़ करें",
        read_more: "और पढ़ें",
        watch_now: "अभी देखें",
        saved: "सहेजा गया",
        save: "सहेजें",
        Sports: "खेल",
        Technology: "प्रौद्योगिकी",
        Science: "विज्ञान",
        Business: "व्यापार",
        Entertainment: "मनोरंजन",
        Politics: "राजनीति",
        Christianity: "ईसाई धर्म"
    },
    ta: {
        dashboard: "டாஷ்போர்டு",
        wishlist: "விருப்பப்பட்டியல்",
        analytics: "பகுப்பாய்வு",
        legal: "சட்ட உதவியாளர்",
        logout: "வெளியேறு",
        search_placeholder: "பிரசங்கங்கள், செய்திகள்...",
        trending_title: "பிரபலமான நற்செய்தி வீடியோக்கள்",
        news_title: "சமீபத்திய கிறிஸ்தவ செய்திகள்",
        admin_panel: "நிர்வாகக் குழு",
        legal_intro: "<p>இந்தியாவில் சிறுபான்மையினர் உரிமைகளுக்கான உங்கள் <b>AI சட்ட உதவியாளர்</b> நான்.</p><p>நீங்கள் என்னிடம் கேள்விகள் கேட்கலாம்:</p><ul><li>கிறிஸ்தவ நிறுவனமாக எனக்கு என்ன உரிமைகள் உள்ளன?</li><li>சிறுபான்மை பள்ளியை பதிவு செய்வது எப்படி?</li><li>பிரிவு 30 என்றால் என்ன?</li></ul>",
        verified_ai_response: "சரிபார்க்கப்பட்ட AI பதில்",
        read_aloud: "சத்தமாகப் படியுங்கள்",
        news_btn: "செய்திகள்",
        videos_btn: "வீடியோக்கள்",
        min_read: "நிமிடம் படித்தல்",
        recently: "சமீபத்தில்",
        legal_disclaimer: "AI தவறுகள் செய்யலாம். அதிகாரப்பூர்வ ஆலோசனைக்கு தகுதிவாய்ந்த சட்ட நிபுணரை அணுகவும்.",
        legal_placeholder: "கேள்விகள் கேளுங்கள்...",
        search_news_placeholder: "செய்தி கட்டுரைகளைத் தேடுங்கள்...",
        search_videos_placeholder: "வீடியோக்களைத் தேடுங்கள்...",
        found_results: "முடிவுகள்",
        no_news: "செய்திகள் எதுவும் இல்லை",
        no_videos: "வீடியோக்கள் எதுவும் இல்லை",
        no_results: "முடிவுகள் எதுவும் இல்லை",
        loading: "ஏற்றுகிறது...",
        search: "தேடு",
        clear: "தெளிவாக்கு",
        read_more: "மேலும் படிக்க",
        watch_now: "இப்போது பார்க்கவும்",
        saved: "சேமிக்கப்பட்டது",
        save: "சேமி",
        Sports: "விளையாட்டு",
        Technology: "தொழில்நுட்பம்",
        Science: "அறிவியல்",
        Business: "வணிகம்",
        Entertainment: "பொழுதுபோக்கு",
        Politics: "அரசியல்",
        Christianity: "கிறிஸ்தவம்"
    }
};
